server:
  port: 8001

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master # 分支名称
      server:
        git:
          uri: https://github.com/lllZLXlll/SpringCloudConfig # git仓库路径
          search-paths: test-config # 仓库路径
          # 仓库连接账号密码，公开仓库没有密码
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:1234@localhost:8761/eureka/
